### PR TITLE
added contaminated sites input files

### PR DESCRIPTION
**Pull request by JeremyFyke**

### CODE REVIEW

**Comment by JeremyFyke** [comment]
Hi @mprov I believe I cleaned up the issue(s) that you ran into in running the DST, that you wanted me to look at prior to a migration to CRIM Github site. I merged this into master via this self-satisfied pull request.  

This cleanup actually involved a slight refactor of DST structure itself to avoid exactly the issue you encountered (was something I intended to do at some point anyways).  Importantly, as a result of this refactor, now, the DST has an initial drop down menu where users can select the sector they're interested in.  And the subsequent tool modifies itself (via read-in of different input files) to 'look' like a tool specific to the selected sector.  Currently, I have prototype building and contaminated site sectors built in (as both these have corresponding input file sets).

Another consequence of this clean up is that you can get rid of the placeholder 'agriculture'/'buildings' toggle button on CRIM dev site - the capability to choose sectors is now hosted entirely within the current tool itself.  Whether or not that's the best option is to be discussed - but at least, for now, it simplifies development/testing and gets rid of the issue that you encountered originally.

@ryan1000000 when you're ready to merge the formatting work you are doing (perhaps once it's CRIM-hosted, unless you can be ready prior to Mathieu's imminent migration?) let me know - the merge may be somewhat manual, given my restructure of some of the base DST code.   FYI:@cpomer10

**Comment by matprov** [comment]
Hi @JeremyFyke @ryan1000000 ,

Repo is now under https://github.com/crim-ca/decision-support-tool
The integrations with the image publishing process is done, as well as the security aspect.
Images are pushed under https://hub.docker.com/repository/docker/crimca/decision-support-tool

Push access is restricted on Dockerhub repo, so only the Github Action can publish new images.
All changes on main branch require PR with at least one approval. We can't accidentally commit on main branch.

You can proceed to deletion of the ECCC-CCCS/dst repo after having transferred issues to the new repo and merged relevant branches.
You can temporarily archive the repo too, if you prefer. This way you won't push to the wrong repo. It's your call, based on your preference.

Don't forget to update your remote Git origin to point to crim-ca Github repo.

@JeremyFyke Nice one for the embedded tool selector. Since it's the exact same process for now, why not. If it becomes cumbersome, we'll advise. You can see what your latest version looks like on the staging page.

**Comment by JeremyFyke** [comment]
Excellent, this is awesome, thanks for this work.  We'll do a cleanup of the ECCC-CCCS repo and then as long as we can commit to (branches of) the CRIM repo and play a role in approving PRs, I think we should just shut the ECCC repo down completely.

**Comment by matprov** [comment]
@JeremyFyke Please give access to "maximeroycrim" in order for him to view this discussion.

You'll then be able to use the Discussions section on the crim-ca/decision-support-tool repo and the Issues to discuss next things you want to do.

You're free to set a meeting whenever you need to schedule the next steps related to the development of this tool.

**Pull request merged**
